trigger:
- master
- pyfilesystem-s3fs-support

jobs:
- job: 'Linux'
  pool:
    vmImage: 'ubuntu-latest'

  strategy:
    matrix:
      Python37:
        python.version: '3.7'

  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
      displayName: 'Use Python $(python.version)'

    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'

    - task: DockerInstaller@0
      displayName: Docker Installer
      inputs:
        dockerVersion: 17.09.0-ce
        releaseType: stable

    - bash: npm install -g yarn
      displayName: "Install Yarn"

    - bash: yarn
      displayName: "Install Deps"

    - script: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
      displayName: 'Install dependencies'

    - script: |
        make lint
      displayName: 'Lint'

    - script: |
        dockerd
        docker run -p 9000:80 --env S3PROXY_AUTHORIZATION=none andrewgaul/s3proxy
        make tests
      displayName: 'Test'

    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testResultsFiles: 'python_junit.xml'
        testRunTitle: 'Publish test results for Python $(python.version) $(manylinux_flag)'

    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/*coverage.xml'

- job: 'Mac'
  pool:
    vmImage: 'macos-10.14'

  strategy:
    matrix:
      Python37:
        python.version: '3.7'

  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
      displayName: 'Use Python $(python.version)'

    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'

    - task: DockerInstaller@0
      displayName: Docker Installer
      inputs:
        dockerVersion: 17.09.0-ce
        releaseType: stable

    - bash: docker run -p 9000:80 --env S3PROXY_AUTHORIZATION=none andrewgaul/s3proxy
      displayName: "Start local S3 server in docker"

    - bash: npm install -g yarn
      displayName: "Install Yarn"

    - bash: yarn
      displayName: "Install Deps"

    - script: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
      displayName: 'Install dependencies'

    - script: |
        make lint
      displayName: 'Lint'

    - script: |
        make tests
      displayName: 'Test'

    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testResultsFiles: 'python_junit.xml'
        testRunTitle: 'Publish test results for Python $(python.version) $(manylinux_flag)'

    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/*coverage.xml'

- job: 'Windows'
  pool:
    vmImage: 'vs2017-win2016'

  strategy:
    matrix:
      Python37:
        python.version: '3.7'

  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
      displayName: 'Use Python $(python.version)'

    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'

    - task: DockerInstaller@0
      displayName: Docker Installer
      inputs:
        dockerVersion: 17.09.0-ce
        releaseType: stable

    - bash: docker run -p 9000:80 --env S3PROXY_AUTHORIZATION=none andrewgaul/s3proxy
      displayName: "Start local S3 server in docker"

    - bash: npm install -g yarn
      displayName: "Install Yarn"

    - bash: yarn
      displayName: "Install Deps"

    - script: |
        which python > python.txt
        set /p PYTHON=<python.txt
        ln -s %PYTHON% %PYTHON%$(python.version)
        python --version
        which python$(python.version)
      displayName: "Which python"

    - script: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
      displayName: 'Install dependencies'

    - script: |
        make lint
      displayName: 'Lint'

    - script: |
        make tests
      displayName: 'Test'

    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testResultsFiles: 'python_junit.xml'
        testRunTitle: 'Publish test results for Python $(python.version) $(manylinux_flag)'

    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/*coverage.xml'
